name: iOS CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  SCHEME: "InstaStory"
  PROJECT: "InstaStory.xcodeproj"
  DESTINATION: 'platform=iOS Simulator,name=iPhone 15'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Xcode derived data
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-xcode-unit-${{ hashFiles('**/*.swift', '**/*.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-unit-
          ${{ runner.os }}-xcode-

    - name: Run Unit Tests
      run: |
        xcodebuild test \
          -project ${{ env.PROJECT }} \
          -scheme ${{ env.SCHEME }} \
          -destination '${{ env.DESTINATION }}' \
          -only-testing:InstaStoryTests \
          CODE_SIGNING_ALLOWED=NO

  ui-tests:
    name: UI Tests
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Xcode derived data
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-xcode-ui-${{ hashFiles('**/*.swift', '**/*.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-ui-
          ${{ runner.os }}-xcode-

    - name: Pre-boot Simulator
      run: |
        xcrun simctl boot "iPhone 15" || true
        xcrun simctl list devices

    - name: Run UI Tests
      run: |
        xcodebuild test \
          -project ${{ env.PROJECT }} \
          -scheme ${{ env.SCHEME }} \
          -destination '${{ env.DESTINATION }}' \
          -only-testing:InstaStoryTestsUI \
          CODE_SIGNING_ALLOWED=NO