name: iOS CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  SCHEME: "InstaStory"
  PROJECT: "InstaStory.xcodeproj"
  IOS_VERSION: "18.0"
  SIMULATOR_NAME: "iPhone SE (3rd generation)"
  DESTINATION: 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=18.0'

jobs:
  build:
    name: Build for Testing
    runs-on: macos-15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Xcode derived data
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-xcode-build-${{ hashFiles('**/*.swift', '**/*.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-build-
          ${{ runner.os }}-xcode-

    - name: Setup iOS Simulator
      run: |
        # List available simulators
        xcrun simctl list devices

        # Create iPhone SE simulator if it doesn't exist
        xcrun simctl create "iPhone SE (3rd generation)" "iPhone SE (3rd generation)" "iOS18.0" || true

        # List devices again to verify
        xcrun simctl list devices

    - name: Build for Testing
      run: |
        xcodebuild build-for-testing \
          -project ${{ env.PROJECT }} \
          -scheme ${{ env.SCHEME }} \
          -destination '${{ env.DESTINATION }}' \
          CODE_SIGNING_ALLOWED=NO

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-products
        path: ~/Library/Developer/Xcode/DerivedData/**/Build/Products
        retention-days: 1

  unit-tests:
    name: Unit Tests
    runs-on: macos-15
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-products
        path: ~/Library/Developer/Xcode/DerivedData/InstaStory/Build/Products

    - name: Run Unit Tests
      run: |
        xcodebuild test-without-building \
          -project ${{ env.PROJECT }} \
          -scheme ${{ env.SCHEME }} \
          -destination '${{ env.DESTINATION }}' \
          -only-testing:InstaStoryTests \
          CODE_SIGNING_ALLOWED=NO

  ui-tests:
    name: UI Tests
    runs-on: macos-15
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-products
        path: ~/Library/Developer/Xcode/DerivedData/InstaStory/Build/Products

    - name: Setup and Boot Simulator
      run: |
        # List available simulators
        xcrun simctl list devices

        # Create iPhone SE simulator if it doesn't exist
        xcrun simctl create "iPhone SE (3rd generation)" "iPhone SE (3rd generation)" "iOS18.0" || true

        # Boot the simulator
        xcrun simctl boot "iPhone SE (3rd generation)" || true

    - name: Run UI Tests
      run: |
        xcodebuild test-without-building \
          -project ${{ env.PROJECT }} \
          -scheme ${{ env.SCHEME }} \
          -destination '${{ env.DESTINATION }}' \
          -only-testing:InstaStoryTestsUI \
          CODE_SIGNING_ALLOWED=NO