name: iOS CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  SCHEME: "InstaStory"
  PROJECT: "InstaStory.xcodeproj"
  DESTINATION: 'platform=iOS Simulator,name=iPhone 16'

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and Test
      run: |
        xcodebuild test \
          -project ${{ env.PROJECT }} \
          -scheme ${{ env.SCHEME }} \
          -destination '${{ env.DESTINATION }}' \
          CODE_SIGNING_ALLOWED=NO